//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diriginte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Diriginte()
        {
            this.Clasas = new HashSet<Clasa>();
        }
    
        public int DiriginteID { get; set; }
        public string Nume { get; set; }
        public string PRENUME { get; set; }
        public string Username { get; set; }
        public string Parola { get; set; }
        public Nullable<int> MateriePredata { get; set; }
        public Nullable<int> Clasa { get; set; }
    
        public virtual MateriiSpecializari MateriiSpecializari { get; set; }
        public virtual Clasa Clasa1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clasa> Clasas { get; set; }
    }
}
