//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Profesor> Profesors { get; set; }
        public virtual DbSet<Specializare> Specializares { get; set; }
        public virtual DbSet<Clasa> Clasas { get; set; }
        public virtual DbSet<Materie> Materies { get; set; }
        public virtual DbSet<MateriiSpecializari> MateriiSpecializaris { get; set; }
        public virtual DbSet<Diriginte> Dirigintes { get; set; }
        public virtual DbSet<MateriiProfesori> MateriiProfesoris { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Absente> Absentes { get; set; }
        public virtual DbSet<NOTA> NOTAs { get; set; }
    
        public virtual int AdaugaClasa(string specializareNume, string denumireClasa)
        {
            var specializareNumeParameter = specializareNume != null ?
                new ObjectParameter("SpecializareNume", specializareNume) :
                new ObjectParameter("SpecializareNume", typeof(string));
    
            var denumireClasaParameter = denumireClasa != null ?
                new ObjectParameter("DenumireClasa", denumireClasa) :
                new ObjectParameter("DenumireClasa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AdaugaClasa", specializareNumeParameter, denumireClasaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> AdminF(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("AdminF", usernameParameter, passwordParameter);
        }
    
        public virtual int StergeClasa(string nume_clasa)
        {
            var nume_clasaParameter = nume_clasa != null ?
                new ObjectParameter("nume_clasa", nume_clasa) :
                new ObjectParameter("nume_clasa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StergeClasa", nume_clasaParameter);
        }
    
        public virtual int ActualizareClasa(Nullable<int> clasaID, string specializareNoua)
        {
            var clasaIDParameter = clasaID.HasValue ?
                new ObjectParameter("ClasaID", clasaID) :
                new ObjectParameter("ClasaID", typeof(int));
    
            var specializareNouaParameter = specializareNoua != null ?
                new ObjectParameter("SpecializareNoua", specializareNoua) :
                new ObjectParameter("SpecializareNoua", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizareClasa", clasaIDParameter, specializareNouaParameter);
        }
    
        public virtual int ModificaSpecializareClasa(string numeClasa, string numeSpecializareNoua)
        {
            var numeClasaParameter = numeClasa != null ?
                new ObjectParameter("NumeClasa", numeClasa) :
                new ObjectParameter("NumeClasa", typeof(string));
    
            var numeSpecializareNouaParameter = numeSpecializareNoua != null ?
                new ObjectParameter("NumeSpecializareNoua", numeSpecializareNoua) :
                new ObjectParameter("NumeSpecializareNoua", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModificaSpecializareClasa", numeClasaParameter, numeSpecializareNouaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> DiriginteF(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("DiriginteF", usernameParameter, passwordParameter);
        }
    
        public virtual int AdaugaDiriginte(string nume, string prenume, string username, string parola, Nullable<int> clasa, Nullable<int> materieSpecializare)
        {
            var numeParameter = nume != null ?
                new ObjectParameter("Nume", nume) :
                new ObjectParameter("Nume", typeof(string));
    
            var prenumeParameter = prenume != null ?
                new ObjectParameter("Prenume", prenume) :
                new ObjectParameter("Prenume", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var parolaParameter = parola != null ?
                new ObjectParameter("Parola", parola) :
                new ObjectParameter("Parola", typeof(string));
    
            var clasaParameter = clasa.HasValue ?
                new ObjectParameter("Clasa", clasa) :
                new ObjectParameter("Clasa", typeof(int));
    
            var materieSpecializareParameter = materieSpecializare.HasValue ?
                new ObjectParameter("MaterieSpecializare", materieSpecializare) :
                new ObjectParameter("MaterieSpecializare", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AdaugaDiriginte", numeParameter, prenumeParameter, usernameParameter, parolaParameter, clasaParameter, materieSpecializareParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> ProfesorF(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ProfesorF", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> StudentF(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("StudentF", usernameParameter, passwordParameter);
        }
    
        public virtual int ActualizareDiriginte(string numeDiriginteSursa, string prenumeDiriginteSursa, string numeDiriginteDestinatar, string prenumeDiriginteDestinatar)
        {
            var numeDiriginteSursaParameter = numeDiriginteSursa != null ?
                new ObjectParameter("NumeDiriginteSursa", numeDiriginteSursa) :
                new ObjectParameter("NumeDiriginteSursa", typeof(string));
    
            var prenumeDiriginteSursaParameter = prenumeDiriginteSursa != null ?
                new ObjectParameter("PrenumeDiriginteSursa", prenumeDiriginteSursa) :
                new ObjectParameter("PrenumeDiriginteSursa", typeof(string));
    
            var numeDiriginteDestinatarParameter = numeDiriginteDestinatar != null ?
                new ObjectParameter("NumeDiriginteDestinatar", numeDiriginteDestinatar) :
                new ObjectParameter("NumeDiriginteDestinatar", typeof(string));
    
            var prenumeDiriginteDestinatarParameter = prenumeDiriginteDestinatar != null ?
                new ObjectParameter("PrenumeDiriginteDestinatar", prenumeDiriginteDestinatar) :
                new ObjectParameter("PrenumeDiriginteDestinatar", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizareDiriginte", numeDiriginteSursaParameter, prenumeDiriginteSursaParameter, numeDiriginteDestinatarParameter, prenumeDiriginteDestinatarParameter);
        }
    
        public virtual int ActualizareDiriginteParolaSiMaterie(string numeDiriginte, string prenumeDiriginte, string parola, Nullable<int> materiePredata)
        {
            var numeDiriginteParameter = numeDiriginte != null ?
                new ObjectParameter("NumeDiriginte", numeDiriginte) :
                new ObjectParameter("NumeDiriginte", typeof(string));
    
            var prenumeDiriginteParameter = prenumeDiriginte != null ?
                new ObjectParameter("PrenumeDiriginte", prenumeDiriginte) :
                new ObjectParameter("PrenumeDiriginte", typeof(string));
    
            var parolaParameter = parola != null ?
                new ObjectParameter("Parola", parola) :
                new ObjectParameter("Parola", typeof(string));
    
            var materiePredataParameter = materiePredata.HasValue ?
                new ObjectParameter("MateriePredata", materiePredata) :
                new ObjectParameter("MateriePredata", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizareDiriginteParolaSiMaterie", numeDiriginteParameter, prenumeDiriginteParameter, parolaParameter, materiePredataParameter);
        }
    
        public virtual ObjectResult<string> StergeDiriginte(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("StergeDiriginte", usernameParameter);
        }
    }
}
