//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MateriiProfesori
    {
        public int MateriiProfesoriID { get; set; }
        public Nullable<int> MaterieID { get; set; }
        public Nullable<int> ProfesorID { get; set; }
    
        public virtual Materie Materie { get; set; }
        public virtual Profesor Profesor { get; set; }
    }
}
